version: '3.5'

services:
    server:
        image: websocket:local-latest
        container_name: websocket-server
        restart: always
        deploy:
            replicas: 1
        ports:
        - "8088:8080"
        environment:
            SERVER_PORT: 8080

